site_name: Stroke Data App
nav:
  - Home: index.md
  - Ressource: ressource.md
  - About: about.md

theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true